description: Welcome to Better Maths. The student run website for students in the School of Mathematics.

sass:
   sourcemap: true

url: "https://bettermathematics.github.io/" # update previous line
domain: "https://bettermathematics.github.io/" # update next line
baseurl: "" # does not include hostname

collections:
    sections:
    pages:
        output: true
        permalink: "/:path"

defaults:
    - scope:
        path: ""
        type: "sections"
      values:
        pinned: false # by default, not pinned
        semester: 100 # "Other" stuff is pushed to the end
        archived: false
        course-acronym: ""
        layout: "section"
        learn: true

    - scope:
        path: "" # an empty string here means all files in the project
        type: "pages"
      values:
        layout: "frontpage"
        show-archived: false
